### ISSUE TITLE
host machine backup

### ISSUE THREAD

**Issue by shantanuo** [severalnines/docker-mysql-pxb#1]
The example shows how to take backup of mysql hosted by another container. But how to I take the backup of mysql installed on host machine?

**Comment by ashraf-s9s** [comment]
Suppose the MySQL datadir is /var/lib/mysql, and you want to store the backup under /storage/backups on the physical host, the full command would be:

``` bash

docker run -it \
-v /var/lib/mysql:/var/lib/mysql \
-v /storage/backups:/backups \
--rm=true \
severalnines/mysql-pxb \
sh -c 'exec innobackupex --host="$hostname" --port="3306" --user=root --password="$rootpassword" /backups'
```
